# Generated by Django 4.0.3 on 2022-04-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_name', models.CharField(blank=True, max_length=10)),
                ('facility_size', models.IntegerField(blank=True)),
                ('no_of_manufacturing_suites', models.IntegerField(blank=True)),
                ('no_of_qc_labs', models.IntegerField(blank=True)),
                ('no_of_process_trains_in_parallel', models.IntegerField(blank=True)),
                ('cleanroom', models.IntegerField(blank=True)),
                ('qc', models.IntegerField(blank=True)),
                ('fixed_capital_investment', models.IntegerField(blank=True)),
                ('no_of_operators', models.IntegerField(blank=True)),
                ('manufacturing_time', models.IntegerField(blank=True)),
            ],
        ),
    ]
